### ISSUE TITLE
overlaying a project or app into an existing directory won't replace conflicting files

### ISSUE THREAD

**Issue by antoniosap** [alesandroLang/docker-django#10]
```
docker run --rm -v "$PWD/src:/usr/django/app" alang/django django-admin startproject demo app
CommandError: /usr/django/app/manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files
```

any ideas for running and expose port 8000 ?

**Comment by alesandroLang** [comment]
Hi @antoniosap,

you are trying to create a new Django project with existing sources.
Django will not override your files. You have to delete your `src` folder first.

**Comment by vinit1102** [comment]
It can happen due to two reasons :
1. You are trying to create a new folder with the exiting folder name.
2. You have previously deleted a folder with this name. Deleted it for some reason. But again trying to create package with this name.

To resolve this follow 

Go to <%System Path%>/PycharmProjects/<%Your Project Name%>/.idea/workspace.xml

edit this file "workspace.xml" and then search with the package name you are trying to create. 
delete that line and save the file.
Now try to run the command again. 

I hope this helps. 

Regards,
